baseURL = 'https://0xpsilocyber.com/'
languageCode = 'en-us'
title = '0x.psilocyber // Infosec & Sweet Snazzy Jams'
theme = 'PaperMod'

[params]
    # This now tells the homepage to list posts from BOTH sections
    mainSections = ["infosec", "music"]

[params.profileMode]
    enabled = true
    title = "0x.psilocyber"
    subtitle = "Infosec & Sweet Snazzy Jams"
    imageUrl = ""
    imageWidth = 120
    imageHeight = 120

[params.socialIcons]
    [params.socialIcons.github]
        name = 'github'
        url = 'https://github.com/0xpsilocyber'
    [params.socialIcons.bluesky]
        name = 'bluesky'
        url = 'https://bsky.app/profile/0xpsilocyber.com'
    [params.socialIcons.spotify]
        name = 'spotify'
        url = 'https://open.spotify.com/playlist/7HmZdRpGVrUh9PN9QyrpjZ'

# Your new, two-button main navigation menu
[[menu.main]]
    identifier = "infosec"
    name = "Infosec"
    url = "/infosec/"
    weight = 10

[[menu.main]]
    identifier = "music"
    name = "Music"
    url = "/music/"
    weight = 20