baseURL = 'https://0xpsilocyber.com/'
languageCode = 'en-us'
title = '0xpsilocyber // Infosec & Sweet Snazzy Jams'
theme = 'PaperMod'

# This new section tells Hugo where your main blog content lives.
[params]
    mainSections = ["posts"]

# This section enables the special homepage layout.
[params.profileMode]
    enabled = true
    title = "0xpsilocyber"
    subtitle = "Infosec & Sweet Snazzy Jams"
    imageUrl = ""
    imageWidth = 120
    imageHeight = 120

# Your social icons will be automatically pulled from here.
[params.socialIcons]
    [params.socialIcons.github]
        name = 'github'
        url = 'https://github.com/0xpsilocyber'

    [params.socialIcons.bluesky]
        name = 'bluesky'
        url = 'https://bsky.app/profile/0xpsilocyber.com'

    [params.socialIcons.spotify]
        name = 'spotify'
        url = 'https://open.spotify.com/playlist/7HmZdRpGVrUh9PN9QyrpjZ'

